version: 2

updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "America/Chicago"

  # Maintain dependencies for npm
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "03:00"
      timezone: "America/Chicago"
      open-pull-requests-limit: 5
    commit-message:
      prefix: "npm"
    groups:
      # Group together all minor and patch updates
      npm:
        update-types:
          - "minor"
          - "patch"
