import './globals.css'
import { Dancing_Script } from 'next/font/google'
// import localFont from 'next/font/local'

const dancing_script = Dancing_Script({ subsets: ['latin'] })
// const print_clearly = localFont({
//   src: '../public/fonts/PrintClearly-GGP.ttf',
//   variable: '--font-print-clearly'
// })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={dancing_script.className}>{children}</body>
    </html>
  )
}
